services:
  db:
    image: postgres:16
    container_name: geogrille-db
    environment:
      POSTGRES_DB: geogrille
      POSTGRES_USER: geogrille
      POSTGRES_PASSWORD: geogrille
    ports:
      - "5432:5432"
    volumes:
      - geogrille_pg:/var/lib/postgresql/data

volumes:
  geogrille_pg:
