server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/geogrille}
    username: ${SPRING_DATASOURCE_USERNAME:geogrille}
    password: ${SPRING_DATASOURCE_PASSWORD:geogrille}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  jwt:
    secret: ${APP_JWT_SECRET:CHANGE_ME_SUPER_SECRET_KEY_32_CHARS_MINIMUM}
    expirationMs: 86400000
